### PR TITLE
remove errant space character

### PR DESCRIPTION
**Pull request by TallTed**
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/rdf-turtle/pull/34.html" title="Last updated on Jul 20, 2023, 8:06 PM UTC (8e1470e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-turtle/34/fe482e6...TallTed:8e1470e.html" title="Last updated on Jul 20, 2023, 8:06 PM UTC (8e1470e)">Diff</a>

### CODE REVIEW

**Review by gkellogg — APPROVED** [review]

**Comment by afs** [comment]
In the preview, it becomes `(U+005EU+005E)`.
Is that intended?

(the diff is broken and showing various things that do not agree with the current doc or the preview)

**Comment by TallTed** [comment]
Yes, the intent is to remove the suggestion that there's a space between, by removing the space between.  There might be some CSS tweak to be made to the `codepoint` class, to make it clearer that these are two codepoints...

Alternatively, the text might be tweaked to describe this as *two* of the singular `U+005E` character, only displayed and identified here as a singlet, until the complete example where there are two `^` between the URI and the lang.

**Review by domel — APPROVED** [review]

**Review by domel — APPROVED** [review]

**Comment by afs** [comment]
Yes - saying the character `^` is `U+005E` would work.

**Comment by gkellogg** [comment]
> Yes, the intent is to remove the suggestion that there's a space between, by removing the space between. There might be some CSS tweak to be made to the `codepoint` class, to make it clearer that these are two codepoints...

We could add a class to one or the other condpoints to add a margin after/before, but to a reader that may just look like a space. In fact, the `^^` are unambiguous as is, as they are UNICODE characters that represent themselves. It's only to someone reading a printed document, where the actual character is not apparent where there is ambiguity.

> Alternatively, the text might be tweaked to describe this as _two_ of the singular `U+005E` character, only displayed and identified here as a singlet, until the complete example where there are two `^` between the URI and the lang.

Probably better to describe it narratively as:

> (using two concatenated `^` characters each having the code point <span class="codepoint">U+005E</span>).

**Review by gkellogg — APPROVED** [review]

**Pull request merged**
